[features]
seeds = false
#[programs.localnet]
[programs.devnet]
#nft_id = "6hphtVVtaUbeK9jBbR7QxXccUC5LgYgarMv19qicHjJy"
metaplex_anchor_nft = "6hphtVVtaUbeK9jBbR7QxXccUC5LgYgarMv19qicHjJy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "devnet"
#wallet = "/Users/i/.config/solana/id.json"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
